/**
 * Typed exceptions, error categories and the error code table.
 *
 * <p>{@link com.shengzhiai.yugu.errors.ErrorTable} is generated by {@code tools/gen-errors.mjs}
 * from {@code spec/errors.json}; do not edit it by hand. Every other class of this package is built
 * on top of that table.
 */
package com.shengzhiai.yugu.errors;
