#!/usr/bin/env python3
# Copyright 2026 优谷雅言 open.shengzhiai.com
# SPDX-License-Identifier: Apache-2.0
"""Generate Sources/STKouyuEngine/core/ygst_errors_table.c from spec/errors.json.

  python3 tools/gen_c_errors.py            write the table
  python3 tools/gen_c_errors.py --check    exit 1 when the committed table is stale

The monorepo generator tools/gen-errors.mjs has no C output, so the STKouyuEngine package keeps
its own generator. The published package carries the generated file; spec/errors.json only
exists in the monorepo.
"""
import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
DEFAULT_SPEC = os.path.join(PKG, "..", "spec", "errors.json")
OUT = os.path.join(PKG, "Sources", "STKouyuEngine", "core", "ygst_errors_table.c")


def c_str(s):
    out = ['"']
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif o < 0x20:
            out.append("\\%03o" % o)
        else:
            # UTF-8 source text; gcc and clang use UTF-8 as the execution character set
            out.append(ch)
    out.append('"')
    return "".join(out)


def row(e):
    return "    {%d, %s, %s, %d, %d, %s}," % (
        e["code"], c_str(e["name"]), c_str(e["category"]), 1 if e["retryable"] else 0,
        int(e.get("http", 0) or 0), c_str(e["message"]))


def render(spec):
    lines = []
    lines.append("/* Generated by tools/gen_c_errors.py from spec/errors.json version %s. Do not edit. */" % spec["version"])
    lines.append('#include "ygst_core.h"')
    lines.append("")
    lines.append("const char *const ygst_table_version = %s;" % c_str(spec["version"]))
    lines.append("")
    for name, key in (("errors", "errors"), ("warnings", "warnings"), ("local", "local")):
        lines.append("const ygst_error_entry ygst_table_%s[] = {" % name)
        for e in spec[key]:
            lines.append(row(e))
        lines.append("};")
        lines.append("const size_t ygst_table_%s_count = sizeof ygst_table_%s / sizeof ygst_table_%s[0];" % (name, name, name))
        lines.append("")
    lines.append("const ygst_compat_entry ygst_table_compat[] = {")
    for e in spec["compatErrIds"]:
        lines.append("    {%d, %s}," % (e["errId"], c_str(e["message"])))
    lines.append("};")
    lines.append("const size_t ygst_table_compat_count = sizeof ygst_table_compat / sizeof ygst_table_compat[0];")
    lines.append("")
    lines.append("const int ygst_table_retryable_http[] = {%s};" % ", ".join(str(x) for x in spec["retryableHttp"]))
    lines.append("const size_t ygst_table_retryable_http_count = sizeof ygst_table_retryable_http / sizeof ygst_table_retryable_http[0];")
    lines.append("")
    lines.append("const char *ygst_http_fallback_category(int status) {")
    lines.append("    switch (status) {")
    for k, v in spec["httpFallback"].items():
        lines.append("    case %d:" % int(k))
        lines.append("        return %s;" % c_str(v))
    lines.append("    default:")
    lines.append("        /* DESIGN 2.4: statuses missing from httpFallback map by class */")
    lines.append("        if (status >= 400 && status <= 499) return \"INVALID_PARAM\";")
    lines.append("        if (status >= 500 && status <= 599) return \"SERVER\";")
    lines.append("        return \"UNKNOWN\";")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", default=DEFAULT_SPEC)
    ap.add_argument("--out", default=OUT)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    if not os.path.isfile(a.spec):
        print("spec not found: %s" % a.spec, file=sys.stderr)
        return 2
    with open(a.spec, encoding="utf-8") as f:
        spec = json.load(f)
    text = render(spec)
    if a.check:
        cur = open(a.out, encoding="utf-8").read() if os.path.isfile(a.out) else None
        if cur != text:
            print("stale: %s (run tools/gen_c_errors.py)" % os.path.relpath(a.out, PKG), file=sys.stderr)
            return 1
        print("C error table up to date (errors.json %s)" % spec["version"])
        return 0
    with open(a.out, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote %s" % os.path.relpath(a.out, PKG))
    return 0


if __name__ == "__main__":
    sys.exit(main())
