// Generated by tools/gen-errors.mjs from spec/errors.json version 2026-10-08. Do not edit.
import Foundation

public struct ErrorTableEntry: Sendable, Equatable {
    public let code: Int
    public let name: String
    public let category: ErrorCategory
    public let retryable: Bool
    public let http: Int
    public let message: String
}

public enum ErrorTable {
    public static let errors: [Int: ErrorTableEntry] = Dictionary(uniqueKeysWithValues: [
        ErrorTableEntry(code: 40001, name: "VALIDATION_ERROR", category: .invalidParam, retryable: false, http: 400, message: "请求参数校验失败"),
        ErrorTableEntry(code: 40100, name: "UNAUTHORIZED", category: .auth, retryable: false, http: 401, message: "未认证，缺少或无效的凭据"),
        ErrorTableEntry(code: 40300, name: "FORBIDDEN", category: .permission, retryable: false, http: 403, message: "无权限，例如 API Key 未授权该 coreType"),
        ErrorTableEntry(code: 40400, name: "NOT_FOUND", category: .notFound, retryable: false, http: 404, message: "资源不存在"),
        ErrorTableEntry(code: 40900, name: "CONFLICT", category: .conflict, retryable: false, http: 409, message: "资源冲突"),
        ErrorTableEntry(code: 40901, name: "IDEMPOTENCY_IN_PROGRESS", category: .conflict, retryable: true, http: 409, message: "同一幂等键的请求仍在处理中，稍后用同一个键重试"),
        ErrorTableEntry(code: 40902, name: "QUOTA_INSUFFICIENT", category: .quota, retryable: false, http: 409, message: "套餐额度和账户余额均不足"),
        ErrorTableEntry(code: 40903, name: "IDEMPOTENCY_KEY_REUSED", category: .conflict, retryable: false, http: 409, message: "幂等键已用于另一个不同的请求"),
        ErrorTableEntry(code: 42900, name: "TOO_MANY_REQUESTS", category: .rateLimit, retryable: true, http: 429, message: "请求过多或评测排队超时，按 Retry-After 稍后重试"),
        ErrorTableEntry(code: 42901, name: "CONCURRENCY_LIMIT", category: .rateLimit, retryable: true, http: 429, message: "并发评测数超出套餐层级限制"),
        ErrorTableEntry(code: 42902, name: "TRIAL_REPORT_DAILY_LIMIT", category: .quota, retryable: false, http: 429, message: "试用层 AI 报告达到每日上限"),
        ErrorTableEntry(code: 42903, name: "SANDBOX_DAILY_LIMIT", category: .quota, retryable: false, http: 429, message: "沙箱密钥当日调用次数达到上限"),
        ErrorTableEntry(code: 50000, name: "INTERNAL_ERROR", category: .server, retryable: true, http: 500, message: "服务器内部错误"),
        ErrorTableEntry(code: 50010, name: "FEATURE_NOT_IMPLEMENTED", category: .server, retryable: false, http: 500, message: "功能未实现"),
        ErrorTableEntry(code: 50200, name: "UPSTREAM_SERVICE_ERROR", category: .upstream, retryable: true, http: 502, message: "上游评测服务暂不可用"),
        ErrorTableEntry(code: 2001, name: "TOKEN_EXPIRED", category: .auth, retryable: false, http: 401, message: "token 已过期，兼容层早期引擎接口也用此码表示缺少鉴权三元组或签名不匹配"),
        ErrorTableEntry(code: 2002, name: "TOKEN_INVALID", category: .auth, retryable: false, http: 401, message: "token 无效，兼容层早期引擎接口也用此码表示时间戳超窗"),
        ErrorTableEntry(code: 2003, name: "SIGNATURE_VERIFICATION_FAILED", category: .auth, retryable: false, http: 401, message: "签名验证失败，兼容层早期引擎接口也用此码表示 appKey 不存在"),
        ErrorTableEntry(code: 2004, name: "SESSION_EXPIRED", category: .auth, retryable: false, http: 401, message: "会话已过期"),
        ErrorTableEntry(code: 2005, name: "TOKEN_BLACKLISTED", category: .auth, retryable: false, http: 401, message: "token 已被列入黑名单"),
        ErrorTableEntry(code: 2006, name: "API_KEY_INVALID", category: .auth, retryable: false, http: 401, message: "API Key 无效"),
        ErrorTableEntry(code: 2007, name: "API_KEY_EXPIRED", category: .auth, retryable: false, http: 401, message: "API Key 已过期"),
        ErrorTableEntry(code: 2008, name: "TOKEN_METADATA_NOT_FOUND", category: .auth, retryable: false, http: 401, message: "token 元数据丢失"),
        ErrorTableEntry(code: 2009, name: "TOKEN_REFRESH_FAILED", category: .auth, retryable: false, http: 401, message: "token 刷新失败"),
        ErrorTableEntry(code: 2010, name: "API_KEY_NOT_FOUND", category: .auth, retryable: false, http: 401, message: "API Key 不存在"),
        ErrorTableEntry(code: 2011, name: "API_KEY_DISABLED", category: .auth, retryable: false, http: 401, message: "API Key 已禁用"),
        ErrorTableEntry(code: 2012, name: "API_KEY_QUOTA_EXCEEDED", category: .quota, retryable: false, http: 400, message: "API Key 配额已超限"),
        ErrorTableEntry(code: 3001, name: "RATE_LIMIT_EXCEEDED_IP", category: .rateLimit, retryable: true, http: 429, message: "请求过于频繁，按来源地址限流"),
        ErrorTableEntry(code: 3002, name: "RATE_LIMIT_EXCEEDED_USER", category: .rateLimit, retryable: true, http: 429, message: "请求过于频繁，按用户限流"),
        ErrorTableEntry(code: 3003, name: "RATE_LIMIT_EXCEEDED_API_KEY", category: .rateLimit, retryable: true, http: 429, message: "请求过于频繁，按 API Key 限流"),
        ErrorTableEntry(code: 1004, name: "USER_DISABLED", category: .permission, retryable: false, http: 400, message: "用户已禁用"),
        ErrorTableEntry(code: 1005, name: "USER_LOCKED", category: .permission, retryable: false, http: 400, message: "用户已锁定"),
        ErrorTableEntry(code: 1012, name: "ACCOUNT_DISABLED", category: .permission, retryable: false, http: 400, message: "账户已禁用"),
        ErrorTableEntry(code: 1013, name: "ACCOUNT_FROZEN", category: .permission, retryable: false, http: 400, message: "账户已冻结"),
        ErrorTableEntry(code: 1310, name: "ACCOUNT_BALANCE_INSUFFICIENT", category: .quota, retryable: false, http: 400, message: "账户余额不足"),
        ErrorTableEntry(code: 1311, name: "ACCOUNT_LEDGER_CONFLICT", category: .conflict, retryable: true, http: 400, message: "账目并发冲突，重试即可"),
    ].map { ($0.code, $0) })

    public static let warnings: [Int: ErrorTableEntry] = Dictionary(uniqueKeysWithValues: [
        ErrorTableEntry(code: 1001, name: "NO_VALID_AUDIO", category: .audio, retryable: false, http: 0, message: "No valid audio detected!"),
        ErrorTableEntry(code: 1002, name: "VOLUME_TOO_LOW", category: .audio, retryable: false, http: 0, message: "Audio volume too low!"),
        ErrorTableEntry(code: 1003, name: "VOLUME_TOO_HIGH", category: .audio, retryable: false, http: 0, message: "Audio volume too high!"),
        ErrorTableEntry(code: 1004, name: "AUDIO_NOISY", category: .audio, retryable: false, http: 0, message: "Audio noisy!"),
        ErrorTableEntry(code: 1005, name: "AUDIO_INCOMPLETE", category: .audio, retryable: false, http: 0, message: "Audio not complete!"),
        ErrorTableEntry(code: 1009, name: "SCORER_DEGRADED", category: .audio, retryable: true, http: 0, message: "scorer degraded"),
    ].map { ($0.code, $0) })

    public static let local: [Int: ErrorTableEntry] = Dictionary(uniqueKeysWithValues: [
        ErrorTableEntry(code: 90001, name: "NETWORK_ERROR", category: .network, retryable: true, http: 0, message: "网络错误，连接失败或被重置"),
        ErrorTableEntry(code: 90002, name: "TIMEOUT", category: .timeout, retryable: true, http: 0, message: "连接或读取超时"),
        ErrorTableEntry(code: 90003, name: "CANCELLED", category: .cancelled, retryable: false, http: 0, message: "调用方取消了请求"),
        ErrorTableEntry(code: 90004, name: "CLIENT_CLOSED", category: .state, retryable: false, http: 0, message: "客户端已关闭"),
        ErrorTableEntry(code: 90005, name: "PROTOCOL_ERROR", category: .protocol, retryable: false, http: 0, message: "响应或帧无法解析"),
        ErrorTableEntry(code: 90006, name: "RECONNECT_EXHAUSTED", category: .network, retryable: false, http: 0, message: "实时连接重连次数用尽"),
        ErrorTableEntry(code: 90007, name: "RESULT_TIMEOUT", category: .timeout, retryable: true, http: 0, message: "结束后等待终评结果超时"),
        ErrorTableEntry(code: 90008, name: "REPLAY_BUFFER_OVERFLOW", category: .state, retryable: false, http: 0, message: "重连重放缓冲超过上限"),
        ErrorTableEntry(code: 90009, name: "INVALID_STATE", category: .state, retryable: false, http: 0, message: "当前会话状态不允许该操作"),
        ErrorTableEntry(code: 90010, name: "INVALID_ARGUMENT", category: .invalidParam, retryable: false, http: 0, message: "调用参数不合法"),
        ErrorTableEntry(code: 90011, name: "TLS_ERROR", category: .network, retryable: false, http: 0, message: "证书校验失败"),
        ErrorTableEntry(code: 90101, name: "AUDIO_TOO_SHORT", category: .audio, retryable: false, http: 0, message: "音频短于 1 秒"),
        ErrorTableEntry(code: 90102, name: "AUDIO_TOO_LONG", category: .audio, retryable: false, http: 0, message: "音频长于 300 秒，整段上传大于 50 MB，或实时评测一轮大于 10 MB"),
        ErrorTableEntry(code: 90103, name: "AUDIO_SILENT", category: .audio, retryable: false, http: 0, message: "音频全程静音"),
        ErrorTableEntry(code: 90104, name: "AUDIO_LOW_VOLUME", category: .audio, retryable: false, http: 0, message: "音量过低"),
        ErrorTableEntry(code: 90105, name: "AUDIO_FORMAT_UNSUPPORTED", category: .audio, retryable: false, http: 0, message: "不是 16 位 PCM 或采样率低于 16000"),
        ErrorTableEntry(code: 90201, name: "RECORDER_PERMISSION_DENIED", category: .permission, retryable: false, http: 0, message: "没有麦克风权限"),
        ErrorTableEntry(code: 90202, name: "RECORDER_UNAVAILABLE", category: .state, retryable: false, http: 0, message: "麦克风被占用或不可用"),
        ErrorTableEntry(code: 90203, name: "RECORDER_ERROR", category: .state, retryable: false, http: 0, message: "录音过程出错"),
    ].map { ($0.code, $0) })

    public static let httpFallback: [Int: ErrorCategory] = [
        400: .invalidParam,
        401: .auth,
        403: .permission,
        404: .notFound,
        405: .invalidParam,
        408: .timeout,
        409: .conflict,
        413: .invalidParam,
        415: .invalidParam,
        422: .invalidParam,
        425: .rateLimit,
        429: .rateLimit,
        500: .server,
        501: .server,
        502: .upstream,
        503: .upstream,
        504: .upstream,
    ]

    public static let retryableHttp: Set<Int> = [408, 425, 429, 500, 502, 503, 504]
}

public enum ErrorCodes {
    public static let validationError = 40001
    public static let unauthorized = 40100
    public static let forbidden = 40300
    public static let notFound = 40400
    public static let conflict = 40900
    public static let idempotencyInProgress = 40901
    public static let quotaInsufficient = 40902
    public static let idempotencyKeyReused = 40903
    public static let tooManyRequests = 42900
    public static let concurrencyLimit = 42901
    public static let trialReportDailyLimit = 42902
    public static let sandboxDailyLimit = 42903
    public static let internalError = 50000
    public static let featureNotImplemented = 50010
    public static let upstreamServiceError = 50200
    public static let tokenExpired = 2001
    public static let tokenInvalid = 2002
    public static let signatureVerificationFailed = 2003
    public static let sessionExpired = 2004
    public static let tokenBlacklisted = 2005
    public static let apiKeyInvalid = 2006
    public static let apiKeyExpired = 2007
    public static let tokenMetadataNotFound = 2008
    public static let tokenRefreshFailed = 2009
    public static let apiKeyNotFound = 2010
    public static let apiKeyDisabled = 2011
    public static let apiKeyQuotaExceeded = 2012
    public static let rateLimitExceededIp = 3001
    public static let rateLimitExceededUser = 3002
    public static let rateLimitExceededApiKey = 3003
    public static let userDisabled = 1004
    public static let userLocked = 1005
    public static let accountDisabled = 1012
    public static let accountFrozen = 1013
    public static let accountBalanceInsufficient = 1310
    public static let accountLedgerConflict = 1311
    public static let wNoValidAudio = 1001
    public static let wVolumeTooLow = 1002
    public static let wVolumeTooHigh = 1003
    public static let wAudioNoisy = 1004
    public static let wAudioIncomplete = 1005
    public static let wScorerDegraded = 1009
    public static let networkError = 90001
    public static let timeout = 90002
    public static let cancelled = 90003
    public static let clientClosed = 90004
    public static let protocolError = 90005
    public static let reconnectExhausted = 90006
    public static let resultTimeout = 90007
    public static let replayBufferOverflow = 90008
    public static let invalidState = 90009
    public static let invalidArgument = 90010
    public static let tlsError = 90011
    public static let audioTooShort = 90101
    public static let audioTooLong = 90102
    public static let audioSilent = 90103
    public static let audioLowVolume = 90104
    public static let audioFormatUnsupported = 90105
    public static let recorderPermissionDenied = 90201
    public static let recorderUnavailable = 90202
    public static let recorderError = 90203
}
