/* Generated by tools/gen_c_errors.py from spec/errors.json version 2026-10-08. Do not edit. */
#include "ygst_core.h"

const char *const ygst_table_version = "2026-10-08";

const ygst_error_entry ygst_table_errors[] = {
    {40001, "VALIDATION_ERROR", "INVALID_PARAM", 0, 400, "请求参数校验失败"},
    {40100, "UNAUTHORIZED", "AUTH", 0, 401, "未认证，缺少或无效的凭据"},
    {40300, "FORBIDDEN", "PERMISSION", 0, 403, "无权限，例如 API Key 未授权该 coreType"},
    {40400, "NOT_FOUND", "NOT_FOUND", 0, 404, "资源不存在"},
    {40900, "CONFLICT", "CONFLICT", 0, 409, "资源冲突"},
    {40901, "IDEMPOTENCY_IN_PROGRESS", "CONFLICT", 1, 409, "同一幂等键的请求仍在处理中，稍后用同一个键重试"},
    {40902, "QUOTA_INSUFFICIENT", "QUOTA", 0, 409, "套餐额度和账户余额均不足"},
    {40903, "IDEMPOTENCY_KEY_REUSED", "CONFLICT", 0, 409, "幂等键已用于另一个不同的请求"},
    {42900, "TOO_MANY_REQUESTS", "RATE_LIMIT", 1, 429, "请求过多或评测排队超时，按 Retry-After 稍后重试"},
    {42901, "CONCURRENCY_LIMIT", "RATE_LIMIT", 1, 429, "并发评测数超出套餐层级限制"},
    {42902, "TRIAL_REPORT_DAILY_LIMIT", "QUOTA", 0, 429, "试用层 AI 报告达到每日上限"},
    {42903, "SANDBOX_DAILY_LIMIT", "QUOTA", 0, 429, "沙箱密钥当日调用次数达到上限"},
    {50000, "INTERNAL_ERROR", "SERVER", 1, 500, "服务器内部错误"},
    {50010, "FEATURE_NOT_IMPLEMENTED", "SERVER", 0, 500, "功能未实现"},
    {50200, "UPSTREAM_SERVICE_ERROR", "UPSTREAM", 1, 502, "上游评测服务暂不可用"},
    {2001, "TOKEN_EXPIRED", "AUTH", 0, 401, "token 已过期，兼容层早期引擎接口也用此码表示缺少鉴权三元组或签名不匹配"},
    {2002, "TOKEN_INVALID", "AUTH", 0, 401, "token 无效，兼容层早期引擎接口也用此码表示时间戳超窗"},
    {2003, "SIGNATURE_VERIFICATION_FAILED", "AUTH", 0, 401, "签名验证失败，兼容层早期引擎接口也用此码表示 appKey 不存在"},
    {2004, "SESSION_EXPIRED", "AUTH", 0, 401, "会话已过期"},
    {2005, "TOKEN_BLACKLISTED", "AUTH", 0, 401, "token 已被列入黑名单"},
    {2006, "API_KEY_INVALID", "AUTH", 0, 401, "API Key 无效"},
    {2007, "API_KEY_EXPIRED", "AUTH", 0, 401, "API Key 已过期"},
    {2008, "TOKEN_METADATA_NOT_FOUND", "AUTH", 0, 401, "token 元数据丢失"},
    {2009, "TOKEN_REFRESH_FAILED", "AUTH", 0, 401, "token 刷新失败"},
    {2010, "API_KEY_NOT_FOUND", "AUTH", 0, 401, "API Key 不存在"},
    {2011, "API_KEY_DISABLED", "AUTH", 0, 401, "API Key 已禁用"},
    {2012, "API_KEY_QUOTA_EXCEEDED", "QUOTA", 0, 400, "API Key 配额已超限"},
    {3001, "RATE_LIMIT_EXCEEDED_IP", "RATE_LIMIT", 1, 429, "请求过于频繁，按来源地址限流"},
    {3002, "RATE_LIMIT_EXCEEDED_USER", "RATE_LIMIT", 1, 429, "请求过于频繁，按用户限流"},
    {3003, "RATE_LIMIT_EXCEEDED_API_KEY", "RATE_LIMIT", 1, 429, "请求过于频繁，按 API Key 限流"},
    {1004, "USER_DISABLED", "PERMISSION", 0, 400, "用户已禁用"},
    {1005, "USER_LOCKED", "PERMISSION", 0, 400, "用户已锁定"},
    {1012, "ACCOUNT_DISABLED", "PERMISSION", 0, 400, "账户已禁用"},
    {1013, "ACCOUNT_FROZEN", "PERMISSION", 0, 400, "账户已冻结"},
    {1310, "ACCOUNT_BALANCE_INSUFFICIENT", "QUOTA", 0, 400, "账户余额不足"},
    {1311, "ACCOUNT_LEDGER_CONFLICT", "CONFLICT", 1, 400, "账目并发冲突，重试即可"},
};
const size_t ygst_table_errors_count = sizeof ygst_table_errors / sizeof ygst_table_errors[0];

const ygst_error_entry ygst_table_warnings[] = {
    {1001, "NO_VALID_AUDIO", "AUDIO", 0, 0, "No valid audio detected!"},
    {1002, "VOLUME_TOO_LOW", "AUDIO", 0, 0, "Audio volume too low!"},
    {1003, "VOLUME_TOO_HIGH", "AUDIO", 0, 0, "Audio volume too high!"},
    {1004, "AUDIO_NOISY", "AUDIO", 0, 0, "Audio noisy!"},
    {1005, "AUDIO_INCOMPLETE", "AUDIO", 0, 0, "Audio not complete!"},
    {1009, "SCORER_DEGRADED", "AUDIO", 1, 0, "scorer degraded"},
};
const size_t ygst_table_warnings_count = sizeof ygst_table_warnings / sizeof ygst_table_warnings[0];

const ygst_error_entry ygst_table_local[] = {
    {90001, "NETWORK_ERROR", "NETWORK", 1, 0, "网络错误，连接失败或被重置"},
    {90002, "TIMEOUT", "TIMEOUT", 1, 0, "连接或读取超时"},
    {90003, "CANCELLED", "CANCELLED", 0, 0, "调用方取消了请求"},
    {90004, "CLIENT_CLOSED", "STATE", 0, 0, "客户端已关闭"},
    {90005, "PROTOCOL_ERROR", "PROTOCOL", 0, 0, "响应或帧无法解析"},
    {90006, "RECONNECT_EXHAUSTED", "NETWORK", 0, 0, "实时连接重连次数用尽"},
    {90007, "RESULT_TIMEOUT", "TIMEOUT", 1, 0, "结束后等待终评结果超时"},
    {90008, "REPLAY_BUFFER_OVERFLOW", "STATE", 0, 0, "重连重放缓冲超过上限"},
    {90009, "INVALID_STATE", "STATE", 0, 0, "当前会话状态不允许该操作"},
    {90010, "INVALID_ARGUMENT", "INVALID_PARAM", 0, 0, "调用参数不合法"},
    {90011, "TLS_ERROR", "NETWORK", 0, 0, "证书校验失败"},
    {90101, "AUDIO_TOO_SHORT", "AUDIO", 0, 0, "音频短于 1 秒"},
    {90102, "AUDIO_TOO_LONG", "AUDIO", 0, 0, "音频长于 300 秒，整段上传大于 50 MB，或实时评测一轮大于 10 MB"},
    {90103, "AUDIO_SILENT", "AUDIO", 0, 0, "音频全程静音"},
    {90104, "AUDIO_LOW_VOLUME", "AUDIO", 0, 0, "音量过低"},
    {90105, "AUDIO_FORMAT_UNSUPPORTED", "AUDIO", 0, 0, "不是 16 位 PCM 或采样率低于 16000"},
    {90201, "RECORDER_PERMISSION_DENIED", "PERMISSION", 0, 0, "没有麦克风权限"},
    {90202, "RECORDER_UNAVAILABLE", "STATE", 0, 0, "麦克风被占用或不可用"},
    {90203, "RECORDER_ERROR", "STATE", 0, 0, "录音过程出错"},
};
const size_t ygst_table_local_count = sizeof ygst_table_local / sizeof ygst_table_local[0];

const ygst_compat_entry ygst_table_compat[] = {
    {20009, "网络或服务端临时故障，可重评，autoRetry 默认重评此码"},
    {60001, "音频文件不存在或不可读"},
    {60002, "音频为空"},
    {60003, "coreType 不支持"},
    {60004, "麦克风不可用或没有录音权限"},
    {60005, "音频短于 1 秒"},
    {60006, "refText 为空"},
    {60007, "引擎未初始化"},
    {60008, "引擎正忙，上一次评测未结束"},
    {60009, "音频大于 50 MB 或长于 300 秒"},
};
const size_t ygst_table_compat_count = sizeof ygst_table_compat / sizeof ygst_table_compat[0];

const int ygst_table_retryable_http[] = {408, 425, 429, 500, 502, 503, 504};
const size_t ygst_table_retryable_http_count = sizeof ygst_table_retryable_http / sizeof ygst_table_retryable_http[0];

const char *ygst_http_fallback_category(int status) {
    switch (status) {
    case 400:
        return "INVALID_PARAM";
    case 401:
        return "AUTH";
    case 403:
        return "PERMISSION";
    case 404:
        return "NOT_FOUND";
    case 405:
        return "INVALID_PARAM";
    case 408:
        return "TIMEOUT";
    case 409:
        return "CONFLICT";
    case 413:
        return "INVALID_PARAM";
    case 415:
        return "INVALID_PARAM";
    case 422:
        return "INVALID_PARAM";
    case 425:
        return "RATE_LIMIT";
    case 429:
        return "RATE_LIMIT";
    case 500:
        return "SERVER";
    case 501:
        return "SERVER";
    case 502:
        return "UPSTREAM";
    case 503:
        return "UPSTREAM";
    case 504:
        return "UPSTREAM";
    default:
        /* DESIGN 2.4: statuses missing from httpFallback map by class */
        if (status >= 400 && status <= 499) return "INVALID_PARAM";
        if (status >= 500 && status <= 599) return "SERVER";
        return "UNKNOWN";
    }
}
