#!/usr/bin/env node
// Generates per-language error tables from spec/errors.json.
// Usage: node tools/gen-errors.mjs           write all outputs
//        node tools/gen-errors.mjs --check   exit 1 if any output differs from the committed file
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const spec = JSON.parse(fs.readFileSync(path.join(ROOT, 'spec/errors.json'), 'utf8'));
const HEADER = 'Generated by tools/gen-errors.mjs from spec/errors.json version ' + spec.version + '. Do not edit.';

const jstr = (s) => JSON.stringify(s);

function javaTable(pkg, className) {
  const row = (e, kind) => `        put(${kind}, ${e.code}, ${jstr(e.name)}, ${jstr(e.category)}, ${e.retryable}, ${e.http ?? 0}, ${jstr(e.message)});`;
  return `// ${HEADER}
package ${pkg};

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/** Error, warning and local code tables. */
public final class ${className} {
    /** One table row. */
    public static final class Entry {
        public final int code;
        public final String name;
        public final String category;
        public final boolean retryable;
        public final int http;
        public final String message;

        Entry(int code, String name, String category, boolean retryable, int http, String message) {
            this.code = code;
            this.name = name;
            this.category = category;
            this.retryable = retryable;
            this.http = http;
            this.message = message;
        }
    }

    public static final Map<Integer, Entry> ERRORS;
    public static final Map<Integer, Entry> WARNINGS;
    public static final Map<Integer, Entry> LOCAL;
    public static final Map<Integer, String> HTTP_FALLBACK;
    public static final int[] RETRYABLE_HTTP = {${spec.retryableHttp.join(', ')}};

    private static Map<Integer, Entry> errors;
    private static Map<Integer, Entry> warnings;
    private static Map<Integer, Entry> local;

    private static void put(int kind, int code, String name, String category, boolean retryable, int http, String message) {
        Map<Integer, Entry> m = kind == 0 ? errors : kind == 1 ? warnings : local;
        m.put(code, new Entry(code, name, category, retryable, http, message));
    }

    static {
        errors = new LinkedHashMap<>();
        warnings = new LinkedHashMap<>();
        local = new LinkedHashMap<>();
${spec.errors.map((e) => row(e, 0)).join('\n')}
${spec.warnings.map((e) => row(e, 1)).join('\n')}
${spec.local.map((e) => row(e, 2)).join('\n')}
        Map<Integer, String> hf = new LinkedHashMap<>();
${Object.entries(spec.httpFallback).map(([k, v]) => `        hf.put(${k}, ${jstr(v)});`).join('\n')}
        ERRORS = Collections.unmodifiableMap(errors);
        WARNINGS = Collections.unmodifiableMap(warnings);
        LOCAL = Collections.unmodifiableMap(local);
        HTTP_FALLBACK = Collections.unmodifiableMap(hf);
    }

${[...spec.errors.map((e) => `    public static final int ${e.name} = ${e.code};`),
   ...spec.warnings.map((e) => `    public static final int W_${e.name} = ${e.code};`),
   ...spec.local.map((e) => `    public static final int ${e.name} = ${e.code};`)].join('\n')}

    private ${className}() {
    }
}
`;
}

function kotlinTable() {
  const row = (e) => `        Entry(${e.code}, ${jstr(e.name)}, ${jstr(e.category)}, ${e.retryable}, ${e.http ?? 0}, ${jstr(e.message)}),`;
  return `// ${HEADER}
package com.shengzhiai.yugu.errors

/** Error, warning and local code tables. */
object ErrorTable {
    data class Entry(
        val code: Int,
        val name: String,
        val category: String,
        val retryable: Boolean,
        val http: Int,
        val message: String,
    )

    val ERRORS: Map<Int, Entry> = listOf(
${spec.errors.map(row).join('\n')}
    ).associateBy { it.code }

    val WARNINGS: Map<Int, Entry> = listOf(
${spec.warnings.map(row).join('\n')}
    ).associateBy { it.code }

    val LOCAL: Map<Int, Entry> = listOf(
${spec.local.map(row).join('\n')}
    ).associateBy { it.code }

    val HTTP_FALLBACK: Map<Int, String> = mapOf(
${Object.entries(spec.httpFallback).map(([k, v]) => `        ${k} to ${jstr(v)},`).join('\n')}
    )

    val RETRYABLE_HTTP: Set<Int> = setOf(${spec.retryableHttp.join(', ')})
}

/** Named code constants. */
object ErrorCodes {
${[...spec.errors.map((e) => `    const val ${e.name} = ${e.code}`),
   ...spec.warnings.map((e) => `    const val W_${e.name} = ${e.code}`),
   ...spec.local.map((e) => `    const val ${e.name} = ${e.code}`)].join('\n')}
}
`;
}

function jsTable() {
  const row = (e) => `  [${e.code}, ${jstr(e.name)}, ${jstr(e.category)}, ${e.retryable}, ${e.http ?? 0}, ${jstr(e.message)}],`;
  return `// ${HEADER}
// ES2017-safe on purpose (no Object.fromEntries): the mini program runtime targets ES2017.
const rows = (list) => {
  const out = {};
  for (let i = 0; i < list.length; i++) {
    const [code, name, category, retryable, http, message] = list[i];
    out[code] = Object.freeze({ code, name, category, retryable, http, message });
  }
  return Object.freeze(out);
};

export const ERROR_TABLE = rows([
${spec.errors.map(row).join('\n')}
]);

export const WARNING_TABLE = rows([
${spec.warnings.map(row).join('\n')}
]);

export const LOCAL_TABLE = rows([
${spec.local.map(row).join('\n')}
]);

export const HTTP_FALLBACK = Object.freeze({
${Object.entries(spec.httpFallback).map(([k, v]) => `  ${k}: ${jstr(v)},`).join('\n')}
});

export const RETRYABLE_HTTP = Object.freeze([${spec.retryableHttp.join(', ')}]);

export const ErrorCodes = Object.freeze({
${[...spec.errors.map((e) => `  ${e.name}: ${e.code},`),
   ...spec.warnings.map((e) => `  W_${e.name}: ${e.code},`),
   ...spec.local.map((e) => `  ${e.name}: ${e.code},`)].join('\n')}
});
`;
}

function jsTypes() {
  return `// ${HEADER}
export interface ErrorTableEntry {
  readonly code: number;
  readonly name: string;
  readonly category: ErrorCategory;
  readonly retryable: boolean;
  readonly http: number;
  readonly message: string;
}
export type ErrorCategory = ${spec.categories.map(jstr).join(' | ')};
export declare const ERROR_TABLE: Readonly<Record<number, ErrorTableEntry>>;
export declare const WARNING_TABLE: Readonly<Record<number, ErrorTableEntry>>;
export declare const LOCAL_TABLE: Readonly<Record<number, ErrorTableEntry>>;
export declare const HTTP_FALLBACK: Readonly<Record<number, ErrorCategory>>;
export declare const RETRYABLE_HTTP: readonly number[];
export declare const ErrorCodes: {
${[...spec.errors.map((e) => `  readonly ${e.name}: ${e.code};`),
   ...spec.warnings.map((e) => `  readonly W_${e.name}: ${e.code};`),
   ...spec.local.map((e) => `  readonly ${e.name}: ${e.code};`)].join('\n')}
};
`;
}

function swiftTable() {
  const row = (e) => `        ErrorTableEntry(code: ${e.code}, name: ${jstr(e.name)}, category: .${camel(e.category)}, retryable: ${e.retryable}, http: ${e.http ?? 0}, message: ${jstr(e.message)}),`;
  return `// ${HEADER}
import Foundation

public struct ErrorTableEntry: Sendable, Equatable {
    public let code: Int
    public let name: String
    public let category: ErrorCategory
    public let retryable: Bool
    public let http: Int
    public let message: String
}

public enum ErrorTable {
    public static let errors: [Int: ErrorTableEntry] = Dictionary(uniqueKeysWithValues: [
${spec.errors.map(row).join('\n')}
    ].map { ($0.code, $0) })

    public static let warnings: [Int: ErrorTableEntry] = Dictionary(uniqueKeysWithValues: [
${spec.warnings.map(row).join('\n')}
    ].map { ($0.code, $0) })

    public static let local: [Int: ErrorTableEntry] = Dictionary(uniqueKeysWithValues: [
${spec.local.map(row).join('\n')}
    ].map { ($0.code, $0) })

    public static let httpFallback: [Int: ErrorCategory] = [
${Object.entries(spec.httpFallback).map(([k, v]) => `        ${k}: .${camel(v)},`).join('\n')}
    ]

    public static let retryableHttp: Set<Int> = [${spec.retryableHttp.join(', ')}]
}

public enum ErrorCodes {
${[...spec.errors.map((e) => `    public static let ${camel(e.name)} = ${e.code}`),
   ...spec.warnings.map((e) => `    public static let w${pascal(e.name)} = ${e.code}`),
   ...spec.local.map((e) => `    public static let ${camel(e.name)} = ${e.code}`)].join('\n')}
}
`;
}

function camel(s) {
  const p = pascal(s);
  return p.charAt(0).toLowerCase() + p.slice(1);
}
function pascal(s) {
  return s.toLowerCase().split('_').map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('');
}

function errorsMd() {
  const yes = (b) => (b ? '是' : '否');
  const lines = [];
  lines.push('# 错误码表', '');
  lines.push(`错误码表版本 ${spec.version}，由 \`spec/errors.json\` 生成，各端 SDK 内置同一份表。`, '');
  lines.push('## 服务端错误码', '');
  lines.push('响应体里的 `code` 字段。“常见 HTTP 状态”为典型值，SDK 先按错误码归类，错误码缺失时再按 HTTP 状态归类。', '');
  lines.push('| 错误码 | 名称 | 常见 HTTP 状态 | 类别 | 可重试 | 含义 |', '|---|---|---|---|---|---|');
  for (const e of spec.errors) lines.push(`| ${e.code} | \`${e.name}\` | ${e.http} | \`${e.category}\` | ${yes(e.retryable)} | ${e.message} |`);
  lines.push('', '## 音频质量警告码', '');
  lines.push('评测结果 `warning` 数组里的码，评分照常返回，不作为异常抛出。SDK 把这些码归为 `AUDIO` 类别。', '');
  lines.push('| 警告码 | 名称 | 原文 | 重新提交可能改善 | 含义 |', '|---|---|---|---|---|');
  for (const e of spec.warnings) lines.push(`| ${e.code} | \`${e.name}\` | \`${e.message}\` | ${yes(e.retryable)} | ${e.hint} |`);
  lines.push('', '## SDK 本地错误码', '');
  lines.push('SDK 在本地发现的问题，没有服务端错误码时使用。', '');
  lines.push('| 错误码 | 名称 | 类别 | 可重试 | 含义 |', '|---|---|---|---|---|');
  for (const e of spec.local) lines.push(`| ${e.code} | \`${e.name}\` | \`${e.category}\` | ${yes(e.retryable)} | ${e.message} |`);
  lines.push('', '## HTTP 状态兜底归类', '');
  lines.push('| HTTP 状态 | 类别 |', '|---|---|');
  for (const [k, v] of Object.entries(spec.httpFallback)) lines.push(`| ${k} | \`${v}\` |`);
  lines.push('', `错误码缺失时可重试的 HTTP 状态：${spec.retryableHttp.join('，')}。`, '');
  lines.push('## 声通平替层 errId', '');
  lines.push('安卓与 iOS 声通平替层在 `onScore` 回调的错误 JSON 里给出 `errId`。服务端错误码原样作为 errId，下表为平替层自有的 errId。', '');
  lines.push('| errId | 含义 |', '|---|---|');
  for (const e of spec.compatErrIds) lines.push(`| ${e.errId} | ${e.message} |`);
  lines.push('');
  return lines.join('\n');
}

const outputs = {
  'java/src/main/java/com/shengzhiai/yugu/errors/ErrorTable.java': javaTable('com.shengzhiai.yugu.errors', 'ErrorTable'),
  'android/yugu-android-sdk/src/main/kotlin/com/shengzhiai/yugu/errors/ErrorTable.kt': kotlinTable(),
  'android-stcompat/stkouyu-compat/src/main/java/com/shengzhiai/yugu/stcompat/internal/ErrorTable.java': javaTable('com.shengzhiai.yugu.stcompat.internal', 'ErrorTable'),
  'web/src/error-table.js': jsTable(),
  'web/types/error-table.d.ts': jsTypes(),
  'miniprogram/src/error-table.js': jsTable(),
  'miniprogram/types/error-table.d.ts': jsTypes(),
  'ios/Sources/YuguCore/ErrorTable.swift': swiftTable(),
  'ERRORS.md': errorsMd(),
};

const check = process.argv.includes('--check');
// --only <substring> limits the run to outputs whose path contains the substring, for example --only ios/
const onlyIdx = process.argv.indexOf('--only');
const only = onlyIdx >= 0 ? process.argv[onlyIdx + 1] : null;
let stale = 0;
for (const [rel, content] of Object.entries(outputs)) {
  if (only && !rel.includes(only)) continue;
  const file = path.join(ROOT, rel);
  if (check) {
    const cur = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (cur !== content) { console.error('stale: ' + rel); stale++; }
  } else {
    // write only on change, so builds watching these files do not see a spurious modification
    const cur = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (cur === content) continue;
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
    console.log('wrote ' + rel);
  }
}
if (check && stale) process.exit(1);
if (check) console.log('error tables up to date');
