// Copyright 2026 优谷雅言 open.shengzhiai.com. Licensed under the Apache License, Version 2.0.
// Public entry of @shengzhiai/yugu-web-sdk. The UMD bundle exposes the same names on window.YuguSDK.

import { CLIENT_DEFAULTS, YuguClient } from './client.js';
import { AudioBufferPolicy, DEFAULT_MAX_REPLAY_BYTES, HeartbeatMode, SessionState, YuguStreamSession } from './session.js';
import { PCM_WORKLET_SOURCE, RecorderState, YuguRecorder } from './recorder.js';
import {
  AudioQualityException,
  AuthException,
  ConflictException,
  ErrorCategory,
  IllegalSessionStateException,
  InvalidParameterException,
  isRetryable,
  NetworkException,
  NotFoundException,
  PermissionException,
  ProtocolViolationException,
  QuotaExceededException,
  RateLimitException,
  RequestCancelledException,
  RequestTimeoutException,
  ServerException,
  WarningCode,
  YuguError,
  YuguErrors,
} from './errors.js';
import { ERROR_TABLE, ErrorCodes, HTTP_FALLBACK, LOCAL_TABLE, RETRYABLE_HTTP, WARNING_TABLE } from './error-table.js';
import {
  computeBackoffDelay,
  computeRetryDelay,
  DEFAULT_RECONNECT_POLICY,
  DEFAULT_RETRY_POLICY,
  parseRetryAfter,
} from './retry.js';
import { buildSignPayload, signHmacSha256 } from './signer.js';
import { generateIdempotencyKey, isValidIdempotencyKey } from './idempotency.js';
import {
  AudioPrecheck,
  encodeWav,
  encodeWavBytes,
  floatToInt16,
  MAX_STREAM_BYTES,
  MAX_UPLOAD_BYTES,
  parseWav,
  precheckAudio,
} from './audio.js';
import { COMPAT_CORE_TYPES, NATIVE_CORE_TYPES, normalizeEvalResult, WARNING_MESSAGES } from './result.js';
import { LogLevel } from './logger.js';
import { bytesToBase64 } from './util.js';
import { DEFAULT_BASE_URL, DEFAULT_WS_BASE_URL, SDK_VERSION } from './version.js';

export {
  YuguClient,
  CLIENT_DEFAULTS,
  YuguStreamSession,
  SessionState,
  AudioBufferPolicy,
  HeartbeatMode,
  DEFAULT_MAX_REPLAY_BYTES,
  YuguRecorder,
  RecorderState,
  PCM_WORKLET_SOURCE,
  YuguError,
  NetworkException,
  RequestTimeoutException,
  AuthException,
  PermissionException,
  InvalidParameterException,
  NotFoundException,
  ConflictException,
  RateLimitException,
  QuotaExceededException,
  ServerException,
  AudioQualityException,
  IllegalSessionStateException,
  RequestCancelledException,
  ProtocolViolationException,
  YuguErrors,
  isRetryable,
  ErrorCategory,
  WarningCode,
  ErrorCodes,
  ERROR_TABLE,
  WARNING_TABLE,
  LOCAL_TABLE,
  HTTP_FALLBACK,
  RETRYABLE_HTTP,
  DEFAULT_RETRY_POLICY,
  DEFAULT_RECONNECT_POLICY,
  computeBackoffDelay,
  computeRetryDelay,
  parseRetryAfter,
  signHmacSha256,
  buildSignPayload,
  generateIdempotencyKey,
  isValidIdempotencyKey,
  AudioPrecheck,
  precheckAudio,
  parseWav,
  encodeWav,
  encodeWavBytes,
  floatToInt16,
  MAX_UPLOAD_BYTES,
  MAX_STREAM_BYTES,
  normalizeEvalResult,
  NATIVE_CORE_TYPES,
  COMPAT_CORE_TYPES,
  WARNING_MESSAGES,
  LogLevel,
  bytesToBase64,
  SDK_VERSION,
  DEFAULT_BASE_URL,
  DEFAULT_WS_BASE_URL,
};

/** Namespace object, also the default export and the UMD global window.YuguSDK. */
const YuguSDK = Object.freeze({
  YuguClient,
  CLIENT_DEFAULTS,
  YuguStreamSession,
  SessionState,
  AudioBufferPolicy,
  HeartbeatMode,
  DEFAULT_MAX_REPLAY_BYTES,
  YuguRecorder,
  RecorderState,
  PCM_WORKLET_SOURCE,
  YuguError,
  NetworkException,
  RequestTimeoutException,
  AuthException,
  PermissionException,
  InvalidParameterException,
  NotFoundException,
  ConflictException,
  RateLimitException,
  QuotaExceededException,
  ServerException,
  AudioQualityException,
  IllegalSessionStateException,
  RequestCancelledException,
  ProtocolViolationException,
  YuguErrors,
  isRetryable,
  ErrorCategory,
  WarningCode,
  ErrorCodes,
  ERROR_TABLE,
  WARNING_TABLE,
  LOCAL_TABLE,
  HTTP_FALLBACK,
  RETRYABLE_HTTP,
  DEFAULT_RETRY_POLICY,
  DEFAULT_RECONNECT_POLICY,
  computeBackoffDelay,
  computeRetryDelay,
  parseRetryAfter,
  signHmacSha256,
  buildSignPayload,
  generateIdempotencyKey,
  isValidIdempotencyKey,
  AudioPrecheck,
  precheckAudio,
  parseWav,
  encodeWav,
  encodeWavBytes,
  floatToInt16,
  MAX_UPLOAD_BYTES,
  MAX_STREAM_BYTES,
  normalizeEvalResult,
  NATIVE_CORE_TYPES,
  COMPAT_CORE_TYPES,
  WARNING_MESSAGES,
  LogLevel,
  bytesToBase64,
  SDK_VERSION,
  DEFAULT_BASE_URL,
  DEFAULT_WS_BASE_URL,
});

export default YuguSDK;
